In [1]:
import numpy as np
import pandas as pd

In [2]:
df_cred=pd.read_csv("tmdb_5000_credits.csv")
df_mov=pd.read_csv("tmdb_5000_movies.csv")

In [3]:
df_mov.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
df_cred.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
df_mov=df_mov.merge(df_cred,on="title")

In [6]:
df_mov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [7]:
df_mov=df_mov[['title','genres','id','keywords','overview','cast','crew']]

In [8]:
df_mov.isnull().sum()

title       0
genres      0
id          0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [9]:
df_mov.dropna(inplace=True)

In [10]:
df_mov.duplicated().sum()

0

In [11]:

df_mov.head()

,title,genres,id,keywords,overview,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
df_mov.loc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [14]:
import ast
df_mov['genres']=df_mov['genres'].apply(convert)

In [15]:
df_mov

,title,genres,id,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,El Mariachi,"[Action, Crime, Thriller]",9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,Newlyweds,"[Comedy, Romance]",72766,[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,Shanghai Calling,[],126186,[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,My Date with Drew,[Documentary],25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [16]:
df_mov['keywords']=df_mov['keywords'].apply(convert)

In [17]:
df_mov

,title,genres,id,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,El Mariachi,"[Action, Crime, Thriller]",9367,"[united states–mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,Newlyweds,"[Comedy, Romance]",72766,[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]",231617,"[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,Shanghai Calling,[],126186,[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,My Date with Drew,[Documentary],25975,"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [18]:
df_mov['cast']=df_mov['cast'].apply(convert)

In [19]:
df_mov['cast']=df_mov['cast'].apply(lambda x: x[:3])

In [20]:
df_mov.iloc[1]['crew']

'[{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photography", "name": "Dariusz Wolski"}, {"credit_id": "52fe4232c3a36847f800b4fd", "department": "Directing", "gender": 2, "id": 1704, "job": "Director", "name": "Gore Verbinski"}, {"credit_id": "52fe4232c3a36847f800b54f", "department": "Production", "gender": 2, "id": 770, "job": "Producer", "name": "Jerry Bruckheimer"}, {"credit_id": "52fe4232c3a36847f800b503", "department": "Writing", "gender": 2, "id": 1705, "job": "Screenplay", "name": "Ted Elliott"}, {"credit_id": "52fe4232c3a36847f800b509", "department": "Writing", "gender": 2, "id": 1706, "job": "Screenplay", "name": "Terry Rossio"}, {"credit_id": "52fe4232c3a36847f800b57f", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "52fe4232c3a36847f800b585", "department": "Editing", "gender": 2, "id": 1722, "job": "Editor", "name": "Craig Wood"}, {"credit_id": "52fe4232c3a36847f800b573", "department": "Sound", "gender": 2, "id": 947, "job": "Original Music Composer", "name": "Hans Zimmer"}, {"credit_id": "52fe4232c3a36847f800b555", "department": "Production", "gender": 2, "id": 2444, "job": "Executive Producer", "name": "Mike Stenson"}, {"credit_id": "52fe4232c3a36847f800b561", "department": "Production", "gender": 2, "id": 2445, "job": "Producer", "name": "Eric McLeod"}, {"credit_id": "52fe4232c3a36847f800b55b", "department": "Production", "gender": 2, "id": 2446, "job": "Producer", "name": "Chad Oman"}, {"credit_id": "52fe4232c3a36847f800b567", "department": "Production", "gender": 0, "id": 2447, "job": "Producer", "name": "Peter Kohn"}, {"credit_id": "52fe4232c3a36847f800b56d", "department": "Production", "gender": 0, "id": 2448, "job": "Producer", "name": "Pat Sandston"}, {"credit_id": "52fe4232c3a36847f800b58b", "department": "Production", "gender": 1, "id": 2215, "job": "Casting", "name": "Denise Chamian"}, {"credit_id": "52fe4232c3a36847f800b597", "department": "Art", "gender": 2, "id": 1226, "job": "Production Design", "name": "Rick Heinrichs"}, {"credit_id": "52fe4232c3a36847f800b59d", "department": "Art", "gender": 2, "id": 553, "job": "Art Direction", "name": "John Dexter"}, {"credit_id": "52fe4232c3a36847f800b591", "department": "Production", "gender": 1, "id": 3311, "job": "Casting", "name": "Priscilla John"}, {"credit_id": "52fe4232c3a36847f800b5a3", "department": "Art", "gender": 1, "id": 4032, "job": "Set Decoration", "name": "Cheryl Carasik"}, {"credit_id": "52fe4232c3a36847f800b5a9", "department": "Costume & Make-Up", "gender": 0, "id": 4033, "job": "Costume Design", "name": "Liz Dann"}, {"credit_id": "52fe4232c3a36847f800b5af", "department": "Costume & Make-Up", "gender": 1, "id": 4034, "job": "Costume Design", "name": "Penny Rose"}, {"credit_id": "56427ce8c3a3686a53000d8b", "department": "Sound", "gender": 2, "id": 5132, "job": "Music Supervisor", "name": "Bob Badami"}, {"credit_id": "55993c15c3a36855db002f33", "department": "Art", "gender": 2, "id": 146439, "job": "Conceptual Design", "name": "James Ward Byrkit"}, {"credit_id": "52fe4232c3a36847f800b5b9", "department": "Costume & Make-Up", "gender": 1, "id": 406204, "job": "Makeup Department Head", "name": "Ve Neill"}, {"credit_id": "56e47f7892514132690017bd", "department": "Crew", "gender": 2, "id": 1259516, "job": "Stunts", "name": "John Dixon"}, {"credit_id": "5740be639251416597000849", "department": "Crew", "gender": 0, "id": 1336716, "job": "CGI Supervisor", "name": "Dottie Starling"}, {"credit_id": "56427c639251412fc8000dc1", "department": "Directing", "gender": 1, "id": 1344278, "job": "Script Supervisor", "name": "Pamela Alch"}, {"credit_id": "57083101c3a3681d320004e6", "department": "Crew", "gender": 0, "id": 1368867, "job": "Special Effects Coordinator", "name": "Allen Hall"}, {"credit_id": "56427d5ec3a3686a62000d4a", "department": "Sound", "gender": 0, "id": 1368884, "job": "Music Editor", "name": "Melissa Muik"}, {"credit_id": "56427c7b9251412fd4000e07", "department": "Directing", "gender": 1, "id": 1395290, "job": "Script Supervisor", "name": "Sharron Reynolds"}, {"credit_id": "56427d2bc3a3686a53000d9b", "department": "Sound", "gender": 0, "id": 1399327, "job": "Music Editor", "name": "Barbara McDermott"}, {"credit_id": "56427cb4c3a3686a53000d87", "department": "Directing", "gender": 1, "id": 1400738, "job": "Script Supervisor", "name": "Karen Golden"}, {"credit_id": "56427d169251412fd4000e23", "department": "Sound", "gender": 0, "id": 1534197, "job": "Music Editor", "name": "Katie Greathouse"}]'

In [21]:
def fetch_dir(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if(i['job']=="Director"):
            L.append(i['name'])
            break
    return L

In [22]:
df_mov['crew']=df_mov['crew'].apply(fetch_dir)

In [23]:
df_mov

,title,genres,id,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,El Mariachi,"[Action, Crime, Thriller]",9367,"[united states–mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,Newlyweds,"[Comedy, Romance]",72766,[],A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4806,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]",231617,"[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,Shanghai Calling,[],126186,[],When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,My Date with Drew,[Documentary],25975,"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger]

In [24]:
df_mov['overview']=df_mov['overview'].apply(lambda x: x.split())

In [25]:
df_mov.head()

,title,genres,id,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [26]:
df_mov['genres']=df_mov['genres'].apply(lambda x:[i.replace(" ","") for i in x])
df_mov['keywords']=df_mov['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
df_mov['cast']=df_mov['cast'].apply(lambda x:[i.replace(" ","") for i in x])
df_mov['crew']=df_mov['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [27]:
df_mov

,title,genres,id,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,Spectre,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,John Carter,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,El Mariachi,"[Action, Crime, Thriller]",9367,"[unitedstates–mexicobarrier, legs, arms, paper...","[El, Mariachi, just, wants, to, play, his, gui...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,Newlyweds,"[Comedy, Romance]",72766,[],"[A, newlywed, couple's, honeymoon, is, upended...","[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4806,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie]",231617,"[date, loveatfirstsight, narration, investigat...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,Shanghai Calling,[],126186,[],"[When, ambitious, New, York, attorney, Sam, is...","[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,My Date with Drew,[Documentary],25975,"[obsession, camcorder, crush, dreamgirl]","[Ever, since, the, second, grade, when, he, fi...","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger]

In [28]:
df_mov['tags']=df_mov['overview']+df_mov['genres']+df_mov['keywords']+df_mov['cast']+df_mov['crew']

In [29]:
df_mov

,title,genres,id,keywords,overview,cast,crew,tags
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,John Carter,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,El Mariachi,"[Action, Crime, Thriller]",9367,"[unitedstates–mexicobarrier, legs, arms, paper...","[El, Mariachi, just, wants, to, play, his, gui...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,Newlyweds,"[Comedy, Romance]",72766,[],"[A, newlywed, couple's, honeymoon, is, upended...","[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie]",231617,"[date, loveatfirstsight, narration, investigat...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,Shanghai Calling,[],126186,[],"[When, ambitious, New, York, attorney, Sam, is...","[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,My Date with Drew,[Documentary],25975,"[obsession, camcorder, crush, dreamgirl]","[Ever, since, the, second, grade, when, he, fi...","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],"[Ever, since, the, second, grade, when, he, fi..."

In [30]:
df=df_mov[['title','id','tags']]

In [31]:
df

,title,id,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,El Mariachi,9367,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,Newlyweds,72766,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,"Signed, Sealed, Delivered",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,Shanghai Calling,126186,"[When, ambitious, New, York, attorney, Sam, is..."
4808,My Date with Drew,25975,"[Ever, since, the, second, grade, when, he, fi..."

In [32]:
df['tags']=df['tags'].apply(lambda x: " ".join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_18316\2623380923.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x: " ".join(x))

In [33]:
df

,title,id,tags
0,Avatar,19995,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,206647,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...
4,John Carter,49529,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,El Mariachi,9367,El Mariachi just wants to play his guitar and ...
4805,Newlyweds,72766,A newlywed couple's honeymoon is upended by th...
4806,"Signed, Sealed, Delivered",231617,"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,Shanghai Calling,126186,When ambitious New York attorney Sam is sent t...
4808,My Date with Drew,25975,Ever since the second grade when he first saw ...

In [34]:
df['tags']=df['tags'].apply(lambda x: x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_18316\3228580152.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x: x.lower())

In [35]:
df

,title,id,tags
0,Avatar,19995,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,285,"captain barbossa, long believed to be dead, ha..."
2,Spectre,206647,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,49026,following the death of district attorney harve...
4,John Carter,49529,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,El Mariachi,9367,el mariachi just wants to play his guitar and ...
4805,Newlyweds,72766,a newlywed couple's honeymoon is upended by th...
4806,"Signed, Sealed, Delivered",231617,"""signed, sealed, delivered"" introduces a dedic..."
4807,Shanghai Calling,126186,when ambitious new york attorney sam is sent t...
4808,My Date with Drew,25975,ever since the second grade when he first saw ...

In [36]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [37]:
def stem(text):
    y=[]
    for i in text.split():
       y.append( ps.stem(i))
    return " ".join(y)

In [38]:
df['tags']=df['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_18316\4230616273.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(stem)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words= 'english',max_features=5000)

In [40]:
vector=cv.fit_transform(df['tags']).toarray()

In [41]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting click (from nltk)
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 2.0 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.0 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp312-cp312-win_amd64.whl (273 kB)
Downloading click-8.1.8-py3-none-any.whl (98 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.1.8 nltk-3.9.1 regex-2024.11.6 tqdm-4.67.1

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [42]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
from sklearn.metrics.pairwise import cosine_distances
distance = cosine_distances(vector)
print(distance)

[[0.         0.91653777 0.9139691  ... 0.95500787 1.         1.        ]
 [0.91653777 0.         0.93936609 ... 0.97621743 1.         0.97384671]
 [0.9139691  0.93936609 0.         ... 0.97548548 1.         1.        ]
 ...
 [0.95500787 0.97621743 0.97548548 ... 0.         0.96037856 0.95770451]
 [1.         1.         1.         ... 0.96037856 0.         0.91285796]
 [1.         0.97384671 1.         ... 0.95770451 0.91285796 0.        ]]

In [44]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)

In [45]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [46]:
def reccomend(movie):
    movie_index=df[df['title']==movie].index[0]
    movies_list=sorted(list(enumerate(similarity[movie_index])),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(df.iloc[i[0]].title)

In [47]:
reccomend("Avatar")

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [111]:
df[df['title']=="Gandhi"]['title']

2026    Gandhi
Name: title, dtype: object

In [116]:
sorted(list(enumerate(similarity[2026])),reverse=True)

[(4805, 0.06745406256199318),
 (4804, 0.04212627318711346),
 (4803, 0.020446520502738267),
 (4802, 0.0),
 (4801, 0.0874907046064271),
 (4800, 0.07335511488571664),
 (4799, 0.04783648732349399),
 (4798, 0.057585923114065324),
 (4797, 0.0),
 (4796, 0.03575992699260758),
 (4795, 0.0),
 (4794, 0.08512565307587486),
 (4793, 0.04914731871829904),
 (4792, 0.036860489038724284),
 (4791, 0.0),
 (4790, 0.0),
 (4789, 0.036860489038724284),
 (4788, 0.03143473067309657),
 (4787, 0.08939981748151894),
 (4786, 0.03382550457458691),
 (4785, 0.10727978097782273),
 (4784, 0.0),
 (4783, 0.09652341781316803),
 (4782, 0.0),
 (4781, 0.05296271413323761),
 (4780, 0.12947085767019723),
 (4779, 0.056750435383916574),
 (4778, 0.054758567819339354),
 (4777, 0.04914731871829904),
 (4776, 0.0),
 (4775, 0.02566635011696727),
 (4774, 0.0),
 (4773, 0.053838190205816545),
 (4772, 0.021739130434782608),
 (4771, 0.03575992699260758),
 (4770, 0.0),
 (4769, 0.0),
 (4768, 0.06745406256199318),
 (4767, 0.03296902366978935),
 (4766, 0.0468864482844545),
 (4765, 0.036860489038724284),
 (4764, 0.0),
 (4763, 0.03940552031195504),
 (4762, 0.04715209600964486),
 (4761, 0.0),
 (4760, 0.0690796948587756),
 (4759, 0.07049073768502413),
 (4758, 0.0),
 (4757, 0.042562826537937436),
 (4756, 0.09430419201928972),
 (4755, 0.023918243661746996),
 (4754, 0.052128603514268686),
 (4753, 0.04662524041201569),
 (4752, 0.026919095102908273),
 (4751, 0.0),
 (4750, 0.036860489038724284),
 (4749, 0.034752402342845795),
 (4748, 0.072051607433002),
 (4747, 0.11058146711617285),
 (4746, 0.0),
 (4745, 0.054758567819339354),
 (4744, 0.0),
 (4743, 0.0797663608445026),
 (4742, 0.036860489038724284),
 (4741, 0.028915746598312014),
 (4740, 0.0601929265428846),
 (4739, 0.0),
 (4738, 0.03806934938134405),
 (4737, 0.03806934938134405),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.02191854858423328),
 (4733, 0.09430419201928972),
 (4732, 0.0781166566864507),
 (4731, 0.0),
 (4730, 0.0834057656228299),
 (4729, 0.05617544147048537),
 (4728, 0.07099970268936748),
 (4727, 0.09695723311274393),
 (4726, 0.02566635011696727),
 (4725, 0.06765100914917382),
 (4724, 0.044455422447438706),
 (4723, 0.040893041005476534),
 (4722, 0.01887800803727588),
 (4721, 0.024239308278185982),
 (4720, 0.052128603514268686),
 (4719, 0.0874907046064271),
 (4718, 0.07372097807744857),
 (4717, 0.030096463271442307),
 (4716, 0.026481357066618805),
 (4715, 0.0),
 (4714, 0.0),
 (4713, 0.0),
 (4712, 0.0),
 (4711, 0.03427955850955305),
 (4710, 0.045501575519329006),
 (4709, 0.0),
 (4708, 0.03940552031195504),
 (4707, 0.04662524041201569),
 (4706, 0.10272767854485401),
 (4705, 0.0643489452087787),
 (4704, 0.028915746598312014),
 (4703, 0.030743773095067286),
 (4702, 0.026481357066618805),
 (4701, 0.0),
 (4700, 0.02948839123097943),
 (4699, 0.050572173742417355),
 (4698, 0.030743773095067286),
 (4697, 0.08512565307587487),
 (4696, 0.026481357066618805),
 (4695, 0.03657584779797276),
 (4694, 0.040505420494269105),
 (4693, 0.027379283909669677),
 (4692, 0.018148850216015693),
 (4691, 0.07175473098524099),
 (4690, 0.043478260869565216),
 (4689, 0.04212627318711346),
 (4688, 0.0659380473395787),
 (4687, 0.03217447260438935),
 (4686, 0.053838190205816545),
 (4685, 0.0),
 (4684, 0.03382550457458691),
 (4683, 0.053838190205816545),
 (4682, 0.013749033305079912),
 (4681, 0.1318760946791574),
 (4680, 0.08075728530872482),
 (4679, 0.040893041005476534),
 (4678, 0.08633316946034313),
 (4677, 0.04662524041201569),
 (4676, 0.02566635011696727),
 (4675, 0.02457365935914952),
 (4674, 0.10223260251369133),
 (4673, 0.026919095102908273),
 (4672, 0.0),
 (4671, 0.0),
 (4670, 0.10016708449412666),
 (4669, 0.0),
 (4668, 0.030096463271442307),
 (4667, 0.12461119656980668),
 (4666, 0.028915746598312014),
 (4665, 0.09968895725584535),
 (4664, 0.02786391062876764),
 (4663, 0.0),
 (4662, 0.056634024111827636),
 (4661, 0.0),
 (4660, 0.0),
 (4659, 0.11350087076783315),
 (4658, 0.024239308278185982),
 (4657, 0.02457365935914952),
 (4656, 0.1057361065275362),
 (4655, 0.0),
 (4654, 0.036860489038724284),
 (4653, 0.0),
 (4652, 0.02786391062876764),
 (4651, 0.036860489038724284),
 (4650, 0.054758567819339354),
 (4649, 0.07699905035090181),
 (4648, 0.0),
 (4647, 0.0),
 (4646, 0.10727978097782273),
 (4645, 0.03296902366978935),
 (4644, 0.11242343760332196),
 (4643, 0.0),
 (4642, 0.0),
 (4641, 0.07372097807744857),
 (4640, 0.0659380473395787),
 (4639, 0.08401285158874369),
 (4638, 0.03217447260438935),
 (4637, 0.03806934938134405),
 (4636, 0.0),
 (4635, 0.03575992699260758),
 (4634, 0.04721921646498856),
 (4633, 0.024239308278185982),
 (4632, 0.0),
 (4631, 0.0),
 (4630, 0.09325048082403138),
 (4629, 0.026481357066618805),
 (4628, 0.0),
 (4627, 0.09143961949493189),
 (4626, 0.02457365935914952),
 (4625, 0.04984447862792268),
 (4624, 0.0),
 (4623, 0.02948839123097943),
 (4622, 0.03143473067309657),
 (4621, 0.1333662673423161),
 (4620, 0.0),
 (4619, 0.0),
 (4618, 0.053838190205816545),
 (4617, 0.09325048082403138),
 (4616, 0.020252710247134553),
 (4615, 0.04914731871829904),
 (4614, 0.08213785172900903),
 (4613, 0.01919530770468844),
 (4612, 0.0),
 (4611, 0.0),
 (4610, 0.043478260869565216),
 (4609, 0.0),
 (4608, 0.043013239361934026),
 (4607, 0.0),
 (4606, 0.03806934938134405),
 (4605, 0.07271792483455794),
 (4604, 0.09223131928520185),
 (4603, 0.0959765385234422),
 (4602, 0.02457365935914952),
 (4601, 0.0),
 (4600, 0.0180129018582505),
 (4599, 0.0),
 (4598, 0.0),
 (4597, 0.03905832834322535),
 (4596, 0.0),
 (4595, 0.06148754619013457),
 (4594, 0.03575992699260758),
 (4593, 0.030096463271442307),
 (4592, 0.10498884552771252),
 (4591, 0.13032150878567172),
 (4590, 0.0),
 (4589, 0.0),
 (4588, 0.0),
 (4587, 0.0),
 (4586, 0.034752402342845795),
 (4585, 0.13240678533309402),
 (4584, 0.0),
 (4583, 0.03940552031195504),
 (4582, 0.0479769765755401),
 (4581, 0.0),
 (4580, 0.0),
 (4579, 0.053838190205816545),
 (4578, 0.07944407119985641),
 (4577, 0.07372097807744857),
 (4576, 0.06255432421712243),
 (4575, 0.02457365935914952),
 (4574, 0.06182446677351863),
 (4573, 0.03382550457458691),
 (4572, 0.0),
 (4571, 0.0),
 (4570, 0.027379283909669677),
 (4569, 0.0),
 (4568, 0.18430244519362143),
 (4567, 0.10640706634484359),
 (4566, 0.0),
 (4565, 0.04004630249535576),
 (4564, 0.0),
 (4563, 0.0),
 (4562, 0.0659380473395787),
 (4561, 0.0),
 (4560, 0.05133270023393454),
 (4559, 0.08347257041177222),
 (4558, 0.0),
 (4557, 0.034752402342845795),
 (4556, 0.07881104062391008),
 (4555, 0.0),
 (4554, 0.03296902366978935),
 (4553, 0.08891084489487741),
 (4552, 0.07490058862731383),
 (4551, 0.04662524041201569),
 (4550, 0.0),
 (4549, 0.0),
 (4548, 0.0),
 (4547, 0.06552975829106539),
 (4546, 0.08695652173913043),
 (4545, 0.034752402342845795),
 (4544, 0.0643489452087787),
 (4543, 0.02492223931396134),
 (4542, 0.03382550457458691),
 (4541, 0.02106313659355673),
 (4540, 0.02457365935914952),
 (4539, 0.03217447260438935),
 (4538, 0.041292006950766694),
 (4537, 0.0),
 (4536, 0.026481357066618805),
 (4535, 0.12297509238026914),
 (4534, 0.045501575519329006),
 (4533, 0.04662524041201569),
 (4532, 0.06082990646724735),
 (4531, 0.0219793491131929),
 (4530, 0.04605312990585041),
 (4529, 0.11409401112293896),
 (4528, 0.044455422447438706),
 (4527, 0.0),
 (4526, 0.05897678246195886),
 (4525, 0.020252710247134553),
 (4524, 0.021739130434782608),
 (4523, 0.0),
 (4522, 0.07530655685082076),
 (4521, 0.05897678246195886),
 (4520, 0.01970276015597752),
 (4519, 0.022750787759664503),
 (4518, 0.09306075431858638),
 (4517, 0.03806934938134405),
 (4516, 0.0),
 (4515, 0.03940552031195504),
 (4514, 0.05296271413323761),
 (4513, 0.10879222762803661),
 (4512, 0.022750787759664503),
 (4511, 0.0),
 (4510, 0.0),
 (4509, 0.0),
 (4508, 0.043478260869565216),
 (4507, 0.0),
 (4506, 0.018148850216015693),
 (4505, 0.026919095102908273),
 (4504, 0.01970276015597752),
 (4503, 0.05897678246195886),
 (4502, 0.042562826537937436),
 (4501, 0.0),
 (4500, 0.020851441405707476),
 (4499, 0.026481357066618805),
 (4498, 0.022750787759664503),
 (4497, 0.030743773095067286),
 (4496, 0.06950480468569159),
 (4495, 0.02566635011696727),
 (4494, 0.0),
 (4493, 0.08512565307587486),
 (4492, 0.0),
 (4491, 0.056750435383916574),
 (4490, 0.06019292654288461),
 (4489, 0.057015007612483966),
 (4488, 0.11145564251507054),
 (4487, 0.019881069312188606),
 (4486, 0.030743773095067286),
 (4485, 0.053838190205816545),
 (4484, 0.0),
 (4483, 0.021506619680967013),
 (4482, 0.0),
 (4481, 0.026064301757134343),
 (4480, 0.0),
 (4479, 0.030096463271442307),
 (4478, 0.10951713563867871),
 (4477, 0.06950480468569159),
 (4476, 0.0),
 (4475, 0.026064301757134343),
 (4474, 0.03296902366978935),
 (4473, 0.03575992699260758),
 (4472, 0.0),
 (4471, 0.03451355138642149),
 (4470, 0.028915746598312014),
 (4469, 0.0),
 (4468, 0.10114434748483471),
 (4467, 0.052128603514268686),
 (4466, 0.05324977701702561),
 (4465, 0.09028938981432692),
 (4464, 0.10869565217391304),
 (4463, 0.03296902366978935),
 (4462, 0.044455422447438706),
 (4461, 0.0),
 (4460, 0.03382550457458691),
 (4459, 0.1180480411624714),
 (4458, 0.022227711223719353),
 (4457, 0.036860489038724284),
 (4456, 0.026919095102908273),
 (4455, 0.054758567819339354),
 (4454, 0.0659380473395787),
 (4453, 0.11326804822365527),
 (4452, 0.10592542826647522),
 (4451, 0.12267912301642961),
 (4450, 0.023026564952925203),
 (4449, 0.019034674690672024),
 (4448, 0.12164383764548428),
 (4447, 0.03575992699260758),
 (4446, 0.08602647872386805),
 (4445, 0.05296271413323761),
 (4444, 0.03217447260438935),
 (4443, 0.0),
 (4442, 0.06765100914917382),
 (4441, 0.036860489038724284),
 (4440, 0.023918243661746996),
 (4439, 0.0802572353905128),
 (4438, 0.0),
 (4437, 0.030096463271442307),
 (4436, 0.0),
 (4435, 0.0659380473395787),
 (4434, 0.05897678246195886),
 (4433, 0.05783149319662403),
 (4432, 0.0),
 (4431, 0.0659380473395787),
 (4430, 0.12248698644899794),
 (4429, 0.03360514063549748),
 (4428, 0.036860489038724284),
 (4427, 0.040505420494269105),
 (4426, 0.027379283909669677),
 (4425, 0.0),
 (4424, 0.0),
 (4423, 0.041292006950766694),
 (4422, 0.022750787759664503),
 (4421, 0.030743773095067286),
 (4420, 0.026919095102908273),
 (4419, 0.0),
 (4418, 0.030743773095067286),
 (4417, 0.0),
 (4416, 0.03143473067309657),
 (4415, 0.03940552031195504),
 (4414, 0.06148754619013457),
 (4413, 0.08425254637422692),
 (4412, 0.03382550457458691),
 (4411, 0.06950480468569159),
 (4410, 0.04662524041201569),
 (4409, 0.0),
 (4408, 0.10951713563867871),
 (4407, 0.07151985398521515),
 (4406, 0.05133270023393454),
 (4405, 0.0),
 (4404, 0.0),
 (4403, 0.08846517369293828),
 (4402, 0.08213785172900903),
 (4401, 0.06745406256199318),
 (4400, 0.0),
 (4399, 0.0),
 (4398, 0.04170288281141495),
 (4397, 0.038720154633118314),
 (4396, 0.0),
 (4395, 0.040893041005476534),
 (4394, 0.0),
 (4393, 0.043478260869565216),
 (4392, 0.041292006950766694),
 (4391, 0.0),
 (4390, 0.06950480468569159),
 (4389, 0.0),
 (4388, 0.2307831656885255),
 (4387, 0.0),
 (4386, 0.0),
 (4385, 0.0),
 (4384, 0.059643207936565815),
 (4383, 0.12719260014977865),
 (4382, 0.09074425108007847),
 (4381, 0.10032154423814099),
 (4380, 0.04605312990585041),
 (4379, 0.050572173742417355),
 (4378, 0.0),
 (4377, 0.04984447862792268),
 (4376, 0.020446520502738267),
 (4375, 0.036860489038724284),
 (4374, 0.04721921646498856),
 (4373, 0.06765100914917382),
 (4372, 0.06384423980690615),
 (4371, 0.021506619680967013),
 (4370, 0.03382550457458691),
 (4369, 0.023918243661746996),
 (4368, 0.034752402342845795),
 (4367, 0.0),
 (4366, 0.022484687520664393),
 (4365, 0.0),
 (4364, 0.03715188083835685),
 (4363, 0.021506619680967013),
 (4362, 0.03806934938134405),
 (4361, 0.05783149319662403),
 (4360, 0.0),
 (4359, 0.05808023194967747),
 (4358, 0.09074425108007847),
 (4357, 0.0),
 (4356, 0.0),
 (4355, 0.08674723979493604),
 (4354, 0.0),
 (4353, 0.08178608201095307),
 (4352, 0.022484687520664393),
 (4351, 0.030096463271442307),
 (4350, 0.0219793491131929),
 (4349, 0.07944407119985641),
 (4348, 0.0),
 (4347, 0.02786391062876764),
 (4346, 0.034752402342845795),
 (4345, 0.0900645092912525),
 (4344, 0.024239308278185982),
 (4343, 0.020446520502738267),
 (4342, 0.040893041005476534),
 (4341, 0.04721921646498856),
 (4340, 0.019881069312188606),
 (4339, 0.02457365935914952),
 (4338, 0.030096463271442307),
 (4337, 0.08425254637422692),
 (4336, 0.045501575519329006),
 (4335, 0.10126355123567277),
 (4334, 0.0439586982263858),
 (4333, 0.0761386987626881),
 (4332, 0.0),
 (4331, 0.0),
 (4330, 0.0),
 (4329, 0.023026564952925203),
 (4328, 0.08075728530872482),
 (4327, 0.07082882469748285),
 (4326, 0.0),
 (4325, 0.02106313659355673),
 (4324, 0.08359173188630292),
 (4323, 0.0),
 (4322, 0.0),
 (4321, 0.034752402342845795),
 (4320, 0.08359173188630292),
 (4319, 0.07194430788361927),
 (4318, 0.0),
 (4317, 0.061339561508214804),
 (4316, 0.09567297464698798),
 (4315, 0.0),
 (4314, 0.05212860351426869),
 (4313, 0.07699905035090181),
 (4312, 0.05783149319662403),
 (4311, 0.07271792483455794),
 (4310, 0.017622684421256033),
 (4309, 0.0),
 (4308, 0.1257389226923863),
 (4307, 0.03217447260438935),
 (4306, 0.0),
 (4305, 0.01787996349630379),
 (4304, 0.0),
 (4303, 0.09430419201928972),
 (4302, 0.0),
 (4301, 0.026919095102908273),
 (4300, 0.036860489038724284),
 (4299, 0.0879173964527716),
 (4298, 0.03382550457458691),
 (4297, 0.0),
 (4296, 0.0),
 (4295, 0.07271792483455794),
 (4294, 0.030743773095067286),
 (4293, 0.0),
 (4292, 0.03143473067309657),
 (4291, 0.036025803716501),
 (4290, 0.03143473067309657),
 (4289, 0.05133270023393454),
 (4288, 0.02360960823249428),
 (4287, 0.08425254637422692),
 (4286, 0.042562826537937436),
 (4285, 0.030743773095067286),
 (4284, 0.022484687520664393),
 (4283, 0.07372097807744857),
 (4282, 0.16484511834894675),
 (4281, 0.0),
 (4280, 0.021506619680967013),
 (4279, 0.07151985398521515),
 (4278, 0.0),
 (4277, 0.03405026123034994),
 (4276, 0.06765100914917382),
 (4275, 0.11326804822365527),
 (4274, 0.0690796948587756),
 (4273, 0.05783149319662403),
 (4272, 0.02492223931396134),
 (4271, 0.028915746598312014),
 (4270, 0.026919095102908273),
 (4269, 0.03143473067309657),
 (4268, 0.030743773095067286),
 (4267, 0.0),
 (4266, 0.023312620206007845),
 (4265, 0.01887800803727588),
 (4264, 0.11420804814403215),
 (4263, 0.044455422447438706),
 (4262, 0.0),
 (4261, 0.0659380473395787),
 (4260, 0.08075728530872482),
 (4259, 0.03575992699260758),
 (4258, 0.11959121830873498),
 (4257, 0.0),
 (4256, 0.03217447260438935),
 (4255, 0.09652341781316803),
 (4254, 0.05897678246195886),
 (4253, 0.020851441405707476),
 (4252, 0.0),
 (4251, 0.0),
 (4250, 0.1180480411624714),
 (4249, 0.0540387055747515),
 (4248, 0.06745406256199318),
 (4247, 0.07259540086406277),
 (4246, 0.03575992699260758),
 (4245, 0.06999256368514169),
 (4244, 0.0),
 (4243, 0.03296902366978935),
 (4242, 0.040211442587699216),
 (4241, 0.036860489038724284),
 (4240, 0.0),
 (4239, 0.12297509238026914),
 (4238, 0.0631894097806702),
 (4237, 0.0),
 (4236, 0.0),
 (4235, 0.03905832834322535),
 (4234, 0.0761386987626881),
 (4233, 0.07409237074573118),
 (4232, 0.0),
 (4231, 0.06255432421712243),
 (4230, 0.0),
 (4229, 0.07151985398521515),
 (4228, 0.023312620206007845),
 (4227, 0.0),
 (4226, 0.11566298639324805),
 (4225, 0.040505420494269105),
 (4224, 0.0528680532637681),
 (4223, 0.08754104448666038),
 (4222, 0.0),
 (4221, 0.05897678246195886),
 (4220, 0.016694514082354443),
 (4219, 0.046368350080138974),
 (4218, 0.0),
 (4217, 0.0),
 (4216, 0.0),
 (4215, 0.12387602085230008),
 (4214, 0.030743773095067286),
 (4213, 0.20236218768597955),
 (4212, 0.04212627318711346),
 (4211, 0.04914731871829904),
 (4210, 0.0),
 (4209, 0.02786391062876764),
 (4208, 0.09325048082403138),
 (4207, 0.07372097807744857),
 (4206, 0.027379283909669677),
 (4205, 0.0),
 (4204, 0.09028938981432692),
 (4203, 0.045501575519329006),
 (4202, 0.05572782125753528),
 (4201, 0.05783149319662403),
 (4200, 0.030096463271442307),
 (4199, 0.026481357066618805),
 (4198, 0.01919530770468844),
 (4197, 0.044455422447438706),
 (4196, 0.030096463271442307),
 (4195, 0.09430419201928972),
 (4194, 0.0),
 (4193, 0.06148754619013457),
 (4192, 0.040893041005476534),
 (4191, 0.026481357066618805),
 (4190, 0.0),
 (4189, 0.0),
 (4188, 0.09210625981170081),
 (4187, 0.08512565307587487),
 (4186, 0.08178608201095307),
 (4185, 0.06668313367115805),
 (4184, 0.07881104062391008),
 (4183, 0.0),
 (4182, 0.0),
 (4181, 0.03382550457458691),
 (4180, 0.022227711223719353),
 (4179, 0.018725147156828457),
 (4178, 0.0631894097806702),
 (4177, 0.041292006950766694),
 (4176, 0.0743037616767137),
 (4175, 0.030096463271442307),
 (4174, 0.14744195615489714),
 (4173, 0.04662524041201569),
 (4172, 0.08178608201095307),
 (4171, 0.09829463743659808),
 (4170, 0.022227711223719353),
 (4169, 0.1257389226923863),
 (4168, 0.0936257357841423),
 (4167, 0.11235088294097074),
 (4166, 0.11242343760332196),
 (4165, 0.02360960823249428),
 (4164, 0.027379283909669677),
 (4163, 0.06950480468569159),
 (4162, 0.07175473098524099),
 (4161, 0.0),
 (4160, 0.03296902366978935),
 (4159, 0.030743773095067286),
 (4158, 0.0601929265428846),
 (4157, 0.013994571159381),
 (4156, 0.17693034738587657),
 (4155, 0.0643489452087787),
 (4154, 0.11959121830873498),
 (4153, 0.022227711223719353),
 (4152, 0.036297700432031385),
 (4151, 0.0),
 (4150, 0.08075728530872482),
 (4149, 0.03821113515845008),
 (4148, 0.02786391062876764),
 (4147, 0.06950480468569159),
 (4146, 0.1333662673423161),
 (4145, 0.040893041005476534),
 (4144, 0.03143473067309657),
 (4143, 0.030743773095067286),
 (4142, 0.10032154423814099),
 (4141, 0.0),
 (4140, 0.04783648732349399),
 (4139, 0.07819290527140303),
 (4138, 0.0),
 (4137, 0.0),
 (4136, 0.0),
 (4135, 0.0),
 (4134, 0.026919095102908273),
 (4133, 0.09652341781316803),
 (4132, 0.07175473098524099),
 (4131, 0.0781166566864507),
 (4130, 0.03143473067309657),
 (4129, 0.0),
 (4128, 0.034752402342845795),
 (4127, 0.06757990980304682),
 (4126, 0.0643489452087787),
 (4125, 0.048478616556371965),
 (4124, 0.0),
 (4123, 0.10114434748483471),
 (4122, 0.045501575519329006),
 (4121, 0.08258401390153339),
 (4120, 0.0),
 (4119, 0.07944407119985641),
 (4118, 0.018148850216015693),
 (4117, 0.0),
 (4116, 0.03940552031195504),
 (4115, 0.06193801042615004),
 (4114, 0.026166715911018646),
 (4113, 0.048478616556371965),
 (4112, 0.0),
 (4111, 0.05296271413323761),
 (4110, 0.0),
 (4109, 0.07949537509361165),
 (4108, 0.02492223931396134),
 (4107, 0.04914731871829904),
 (4106, 0.03575992699260758),
 (4105, 0.02786391062876764),
 (4104, 0.01774992567234187),
 (4103, 0.09287970209589212),
 (4102, 0.030743773095067286),
 (4101, 0.11917591430622479),
 (4100, 0.01970276015597752),
 (4099, 0.0439586982263858),
 (4098, 0.06765100914917382),
 (4097, 0.0),
 (4096, 0.06993786061802354),
 (4095, 0.04662524041201569),
 (4094, 0.043478260869565216),
 (4093, 0.048478616556371965),
 (4092, 0.05897678246195886),
 (4091, 0.03575992699260758),
 (4090, 0.09890707100936805),
 (4089, 0.027379283909669677),
 (4088, 0.024239308278185982),
 (4087, 0.07082882469748285),
 (4086, 0.036025803716501),
 (4085, 0.04496937504132879),
 (4084, 0.0),
 (4083, 0.07819290527140303),
 (4082, 0.06193801042615005),
 (4081, 0.0),
 (4080, 0.0651289609025836),
 (4079, 0.0),
 (4078, 0.043478260869565216),
 (4077, 0.023918243661746996),
 (4076, 0.0),
 (4075, 0.036297700432031385),
 (4074, 0.03575992699260758),
 (4073, 0.0),
 (4072, 0.0),
 (4071, 0.015807436935466976),
 (4070, 0.0),
 (4069, 0.042562826537937436),
 (4068, 0.08695652173913043),
 (4067, 0.09325048082403137),
 (4066, 0.10032154423814099),
 (4065, 0.04170288281141495),
 (4064, 0.0),
 (4063, 0.048478616556371965),
 (4062, 0.03940552031195504),
 (4061, 0.043478260869565216),
 (4060, 0.040893041005476534),
 (4059, 0.06019292654288461),
 (4058, 0.07372097807744857),
 (4057, 0.03976213862437721),
 (4056, 0.0),
 (4055, 0.06765100914917382),
 (4054, 0.0),
 (4053, 0.02457365935914952),
 (4052, 0.06148754619013457),
 (4051, 0.10425720702853737),
 (4050, 0.03940552031195504),
 (4049, 0.056634024111827636),
 (4048, 0.014527887622923615),
 (4047, 0.0),
 (4046, 0.0),
 (4045, 0.0682523632789935),